services:
  tibco-hub:
    image: ${HUB_DOCKER_IMAGE:-pdx/tibco-hub}
    build:
      context: ..
      dockerfile: build/platform/Dockerfile
    depends_on:
      - db
    ports:
      - 7007:7007
    # mount your own config
    # volumes:
    #   - ${PWD}/../app-config.yaml:/app/app-config.local.yaml
    environment:
      # host defined as service in docker-compose.yml
      POSTGRES_SERVICE_HOST: 'db'
      POSTGRES_HOST: 'db'
      POSTGRES_SERVICE_PORT: '${POSTGRES_PORT}'
      POSTGRES_PORT: '${POSTGRES_PORT}'
      POSTGRES_SERVICE_USER: '${POSTGRES_USER}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_SERVICE_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      TIBCO_CLOUD_TOKEN: '${TIBCO_CLOUD_TOKEN}'
      AUTH_GITHUB_CLIENT_ID: '${AUTH_GITHUB_CLIENT_ID}'
      AUTH_GITHUB_CLIENT_SECRET: '${AUTH_GITHUB_CLIENT_SECRET}'
      GITHUB_TOKEN: '${GITHUB_TOKEN}'
      AUTH_TIBCO_CLIENT_ID: '${AUTH_TIBCO_CLIENT_ID}'
      AUTH_TIBCO_CLIENT_SECRET: '${AUTH_TIBCO_CLIENT_SECRET}'
      AUTH_TIBCO_AUTHORIZATION_URL: '${AUTH_TIBCO_AUTHORIZATION_URL}'
      AUTH_TIBCO_TOKEN_URL: '${AUTH_TIBCO_TOKEN_URL}'
      HUB_CONFIGFILE: app-config.yaml
      NODE_ENV: dev
      LOG_LEVEL: debug
